In [25]:
# Importing the necessary libraries

import pandas as pd
import numpy as np
import seaborn as sn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

import warnings
warnings.filterwarnings ('ignore')

In [26]:
# Loading the Mall_Customers dataset

df = pd.read_csv ('Training Dataset.csv')
df.head ()

CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)  \
0           1    Male   19                  15                      39   
1           2    Male   21                  15                      81   
2           3  Female   20                  16                       6   
3           4  Female   23                  16                      77   
4           5  Female   31                  17                      40   

   Cluster Labels  
0               3  
1               4  
2               3  
3               4  
4               3

In [27]:
# Preprocessing data

df.isnull ().sum ()

CustomerID                0
Genre                     0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
Cluster Labels            0
dtype: int64

In [28]:
# Creating the training and testing data

X = df.iloc[:, [3, 4]].values
Y = df.iloc[:, 5].values

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)

In [29]:
# Feature Scaling

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [30]:
# Fitting Logistic Regression to the Training set

log_reg = LogisticRegression(random_state = 0)
log_reg.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [31]:
# Predicting the Test set results

y_pred = log_reg.predict(X_test)

In [32]:
# Making the Confusion Matrix

cm = confusion_matrix(y_test, y_pred)
print('\n Confusion Matrix : ')
print( "\n", cm)
print('\n True positive = ', cm[0][0])
print('\n False positive = ', cm[0][1])
print('\n False negative = ', cm[1][0])
print('\n True negative = ', cm[1][1])


 Confusion Matrix : 

 [[11  0  0  0  0]
 [ 0 16  0  0  0]
 [ 0  1  9  0  0]
 [ 0  0  0  8  0]
 [ 0  1  0  0  4]]

 True positive =  11

 False positive =  0

 False negative =  0

 True negative =  16


In [33]:
print('\n Accuracy: {:.2f}\n'.format(accuracy_score(y_test, y_pred)))
print('\n Error Rate : {:.2f}\n'.format(1 - accuracy_score(y_test, y_pred)))

print('\n Micro Precision: {:.2f}'.format(precision_score(y_test, y_pred, average='micro')))
print('\n Micro Recall: {:.2f}'.format(recall_score(y_test, y_pred, average='micro')))
print('\n Micro F1-score: {:.2f}\n'.format(f1_score(y_test, y_pred, average='micro')))

print('\n Macro Precision: {:.2f}'.format(precision_score(y_test, y_pred, average='macro')))
print('\n Macro Recall: {:.2f}'.format(recall_score(y_test, y_pred, average='macro')))
print('\n Macro F1-score: {:.2f}\n'.format(f1_score(y_test, y_pred, average='macro')))

print('\n Weighted Precision: {:.2f}'.format(precision_score(y_test, y_pred, average='weighted')))
print('\n Weighted Recall: {:.2f}'.format(recall_score(y_test, y_pred, average='weighted')))
print('\n Weighted F1-score: {:.2f}'.format(f1_score(y_test, y_pred, average='weighted')))


 Accuracy: 0.96


 Error Rate : 0.04


 Micro Precision: 0.96

 Micro Recall: 0.96

 Micro F1-score: 0.96


 Macro Precision: 0.98

 Macro Recall: 0.94

 Macro F1-score: 0.96


 Weighted Precision: 0.96

 Weighted Recall: 0.96

 Weighted F1-score: 0.96
